CREATE DATABASE inlock_games_tarde;
GO

USE inlock_games_tarde;
GO

CREATE TABLE ESTUDIO(
	idEstudio SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEstudio VARCHAR(20) NOT NULL

);
GO

CREATE TABLE JOGOS(
	idJogo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIO(idEstudio),
	nomeJogo VARCHAR(35),
	descricao VARCHAR(150),
	dataLancamento DATE,
	valor VARCHAR(10)

);
GO

CREATE TABLE TIPO_USUARIO(
	idTipoUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	titulo VARCHAR(15) NOT NULL

);
GO

CREATE TABLE USUARIO(
	idUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
	idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPO_USUARIO(idTipoUsuario),
	email VARCHAR(30) NOT NULL,
	senha VARCHAR(30) NOT NULL

);
GO